### ISSUE TITLE
Blank White Screen

### ISSUE THREAD

**Issue by johnpaulmedina** [atom-archive/terminal#25]
Confirmed and installed all dependencies however when terminal opens I only see a blank white screen. Can't run any commands. I also thought maybe it was a theme issue and swapped it out but nothing.

**Comment by adrianlee44** [comment]
I'm getting the same problem with this package. I see two exceptions thrown in Developer Tools console.

```
Module version mismatch. Expected 13, got 11. Error: Module version mismatch. Expected 13, got 11.
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)
  at Object.<anonymous> (/Users/adrian/.atom/packages/terminal/node_modules/pty.js/lib/pty.js:10:11)
  at Module._compile (module.js:455:26)
  at Object.Module._extensions..js (module.js:473:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)
  at Object.<anonymous> (/Users/adrian/.atom/packages/terminal/node_modules/pty.js/index.js:2:18)
  at Module._compile (module.js:455:26)
  at Object.Module._extensions..js (module.js:473:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)
  at Object.<anonymous> (/Users/adrian/.atom/packages/terminal/lib/terminal-process.coffee:1:7)
  at Object.<anonymous> (/Users/adrian/.atom/packages/terminal/lib/terminal-process.coffee:1:1)
  at Module._compile (module.js:455:26)
  at Object.requireCoffeeScript [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/coffee-cache.js:64:19)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task-bootstrap.js:95:13)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task-bootstrap.js:97:4)
  at Module._compile (module.js:455:26)
  at Object.Module._extensions..js (module.js:473:10)
  at Module.load (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)
  at [eval]:3:1
  at Object.exports.runInThisContext (vm.js:70:17)
  at Object.<anonymous> ([eval]-wrapper:6:22)
  at Module._compile (module.js:455:26)
  at evalScript (node.js:658:25)
  at startup (node.js:90:7)
  at node.js:1037:3
```

and 

```
Cannot call method 'bind' of null TypeError: Cannot call method 'bind' of null
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task-bootstrap.js:82:24)
  at process.EventEmitter.emit (events.js:104:17)
  at handleMessage (child_process.js:318:10)
  at Pipe.channel.onread (child_process.js:346:11)
```

**Comment by zcbenz** [comment]
Can you `rm -rf node_modules && apm install .` under the terminal package's directory and see if it works?

**Comment by adrianlee44** [comment]
That fixed it for me. Thanks @zcbenz.

**Comment by johnpaulmedina** [comment]
I ran the above code and this is what I get

jp@John-Pauls-MacBook-Pro ~/.atom/packages/terminal (master)$ rm -rf node_modules && apm install .
Installing modules ✗

> pty.js@0.2.4 install /Users/jp/.atom/packages/terminal/node_modules/pty.js
> node-gyp rebuild

  CXX(target) Release/obj.target/pty/src/unix/pty.o

npm http GET https://registry.npmjs.org/emissary
npm http GET http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/guid/0.0.10
npm http 200 http://gh-contractor-zcbenz.s3.amazonaws.com/temp/pty.js-0.2.4.tgz
npm http 304 https://registry.npmjs.org/guid/0.0.10
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/nan/0.7.0
npm http GET https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/nan/0.7.0
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/rimraf
../src/unix/pty.cc:37:10: fatal error: '/usr/include/util.h' file not found
#include </usr/include/util.h>
         ^
1 error generated.
make: **\* [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.1.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jp/.atom/packages/terminal/node_modules/pty.js
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! pty.js@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.4 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--userconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "install" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /Users/jp/.atom/packages/terminal
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jp/.atom/packages/terminal/npm-debug.log
npm ERR! not ok code 0

**Comment by alessioalex** [comment]
`rm -rf node_modules && apm install .` fixed it for me

**Comment by felixjung** [comment]
`rm -rf node_modules && apm install .` does not do anything for me unfortunately.

**Comment by kitten** [comment]
@johnpaulmedina @feju Just clone the latest version of pty.js:

``` shell
cd terminal/node_modules
rm -rf pty.js
git clone https://github.com/chjj/pty.js/
cd pty.js
apm install .
cd ../..
apm install .
```

**Comment by rdconsolo** [comment]
Ubuntu 16.04 (x64) new installation always gives me the white screen running atom (even after running all commands previously suggested here).

edit: solved. remove atom, remove Atom folder (~/.config), remove .atom folder (~), install atom.
